#!/bin/sh
mount -a
mkdir -p /var/run
cat /etc_ro/motd
#nvram_daemon&
#goahead&

#for telnet debugging
telnetd

#for syslogd
mkdir -p /var/log

/sbin/internet.sh
/sbin/ntp.sh
/sbin/insmod /etc_ro/rt5350sta.ko
/bin/iqomgr
